services:
  architecture:
    image: structurizr/lite
    ports:
      - 8080:8080
    volumes:
      - ./:/usr/local/structurizr
    #environment:
    # Uncomment to load a subdirectory workspace
    #  - STRUCTURIZR_WORKSPACE_PATH=blog

