name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          lfs: 'true'
      
      - name: Pull LFS files
        run: git lfs pull

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: cd website && npm install -g pnpm && pnpm i

      - name: Build project
        run: cd website && pnpm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: ghp-prod-files
          path: ./website/dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ghp-prod-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
